### PR TITLE
feat: neg operator

### PR DESCRIPTION
**Pull request by 0x73e**
## Pull Request type

Closes https://github.com/gizatechxyz/orion/issues/362

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Missing [Neg](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Neg) operator.

Issue Number: N/A

## What is the new behavior?
Implements [Neg](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Neg) operator.

- Implemented [Neg](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Neg) operator
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by 0x73e** [comment]
@raphaelDkhn I couldn't find any contribution guidelines in the repo. Please let me know if any docs/linting/tests, etc need to be done before PR is merged. Thanks

**Comment by raphaelDkhn** [comment]
> @raphaelDkhn I couldn't find any contribution guidelines in the repo. Please let me know if any docs/linting/tests, etc need to be done before PR is merged. Thanks

Thanks @0x73e, I will review later todays. [Here](https://orion.gizatech.xyz/framework/contribute) is the contribution guideline. [Here](https://orion.gizatech.xyz/academy/tutorials/implement-new-operators-in-orion) you can find a step-by-step tuto to contribute to Orion. If I see anything missing during my review, I let you know :)

**Comment by 0x73e** [comment]
Thanks, totally missed this

**Comment by raphaelDkhn** [comment]
LGTM! Good first PR @0x73e thanks!

Just three small things that was missing:
- Don't forget to add [trait description here](https://github.com/gizatechxyz/orion/blob/f862acb7e2dbba7535608ec4fd00e6e363b24ce6/src/operators/tensor/core.cairo#L59). When you run docgen, it will create links in the doc. 
- Add operator in [compatibility file](https://github.com/gizatechxyz/orion/blob/f862acb7e2dbba7535608ec4fd00e6e363b24ce6/docs/framework/compatibility.md?plain=1#L21)
- Add operator in [Summary file](https://github.com/gizatechxyz/orion/blob/f862acb7e2dbba7535608ec4fd00e6e363b24ce6/docs/SUMMARY.md?plain=1#L62)

**Review by raphaelDkhn — APPROVED** [review]

**Comment by raphaelDkhn** [comment]
@all-contributors add @0x73e for code

**Pull request merged**
