### PR TITLE
Arccos implementation 

### PR DESCRIPTION
**Pull request by hakymulla**
Arccos implementation and tests

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: 85

## What is the new behavior?

- Arccos implemetion for fixed type 
- Arccos implemetion for tensor

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

**Comment by raphaelDkhn** [comment]
Thanks @hakymulla !! Good PR, however it's missing the Tensor<i8> implementation. Did you pull the last changes from dev branch?

**Comment by hakymulla** [comment]
Yes, i pulled the last changes from dev branch.

**Comment by raphaelDkhn** [comment]
> Yes, i pulled the last changes from dev branch. That's weird, i did the tensor implementation.

Hmmm, are you sure you pushed to remote branch?

**Comment by hakymulla** [comment]
yes, i created a new branch hakymulla:new_branch and made my changes in it, and created a pull request gizatechxyz:develop <-  hakymulla:new_branch. i'm not sure what i'm doing wrong and how can i rectify this?

**Pull request closed without merging**
