### PR TITLE
fix #71: update linear test import

### LINKED ISSUE #71: bug: linear test not running
# Bug Report

**Orion version:**

https://github.com/gizatechxyz/orion/commit/e2608c152c21c6f0d6d5d0cc14a5e73a100131cc

**Current behavior:**
Linear tests not running because of improper import

**Expected behavior:**
All tests should run including tests in the `linear_test.cairo` file

**Steps to reproduce:**
`scarb run test`

**Related code:**

**Other information:**

### PR DESCRIPTION
**Pull request by ojetokun**
## Pull Request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?
Tests in `linear_test.cairo` do not run when `scarb run test` is run 

Issue Number: #71

## What is the new behavior?
Tests in `linear_test.cairo` now work when `scarb run test` is run

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by franalgaba — COMMENTED** [review]
The `linear_test.cairo` shouldn't go under `src/tests/operators/nn/functional`? @raphaelDkhn . Nevertheless, thank you @ojetokun for submitting the PR 🙏

**Comment by ojetokun** [comment]
Sure!

**Comment by ojetokun** [comment]
@franalgaba I can update that. I'll do that now

**Comment by ojetokun** [comment]
@franalgaba @raphaelDkhn  pushed

**Review by raphaelDkhn — APPROVED** [review]

**Pull request merged**
