### PR TITLE
Refactor: Support generic types

### PR DESCRIPTION
**Pull request by raphaelDkhn**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [X] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Currently, each function is implemented for each data type. This is not scalable, and modular, as it's more difficult to implement new data types for Tensor or NN traits. 

## What is the new behavior?

- Refactored all functions to support generic types
- Remove tensor extra param
- Update tests
- Update nodegen
- Update doc

## Does this introduce a breaking change?

- [X] Yes
- [ ] No

### CODE REVIEW

**Review by franalgaba — APPROVED** [review]

**Comment by raphaelDkhn** [comment]
@all-contributors please add @dincerguner for code

**Comment by raphaelDkhn** [comment]
https://github.com/all-contributors please add @dincerguner for code

**Comment by raphaelDkhn** [comment]
@all-contributors please add @dincerguner for code

**Comment by raphaelDkhn** [comment]
https://github.com/all-contributors please add @dincerguner for code

**Comment by raphaelDkhn** [comment]
@all-contributors please add @dincerguner for code

**Comment by raphaelDkhn** [comment]
@all-contributors please add @dincerguner for code

**Pull request merged**
