### PR TITLE
Feat binary class in tree_ensemble_classifier operator

### PR DESCRIPTION
**Pull request by HappyTomatoo**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: [506](https://github.com/gizatechxyz/orion/issues/506)

## What is the new behavior?

- Implement binary classification functionality in the [tree_ensemble_classifier](https://github.com/gizatechxyz/orion/blob/main/src/operators/ml/tree_ensemble/tree_ensemble_classifier.cairo)operator.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by raphaelDkhn — COMMENTED** [review]
@HappyTomatoo Can you write tests for this please?

**Comment by HappyTomatoo** [comment]
@raphaelDkhn Yes, I'll add that later

**Comment by HappyTomatoo** [comment]
@raphaelDkhn Binary class test cases have been added.

**Review by raphaelDkhn — APPROVED** [review]
LGTM!

**Pull request merged**
