### PR TITLE
Feat bitwise and

### PR DESCRIPTION
**Pull request by bilgin-kocak**
## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: #301 

## What is the new behavior?

- Elementwise  bitwise and operation between two tensors added.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

I added some test for fixed point representation.

### CODE REVIEW

**Comment by raphaelDkhn** [comment]
LGTM! @bilgin-kocak thanks!

Just four small things that was missing:

* Run `scarb run docgen` to generate the doc.
* Don't forget to add [trait description here](https://github.com/gizatechxyz/orion/blob/f862acb7e2dbba7535608ec4fd00e6e363b24ce6/src/operators/tensor/core.cairo#L59). When you run docgen, it will create links in the doc.
* Add operator in [compatibility file](https://github.com/gizatechxyz/orion/blob/f862acb7e2dbba7535608ec4fd00e6e363b24ce6/docs/framework/compatibility.md?plain=1#L21)
* Add operator in [Summary file](https://github.com/gizatechxyz/orion/blob/f862acb7e2dbba7535608ec4fd00e6e363b24ce6/docs/SUMMARY.md?plain=1#L62)

**Comment by bilgin-kocak** [comment]
Docs are generated and added

**Comment by raphaelDkhn** [comment]
LGTM

**Comment by raphaelDkhn** [comment]
@all-contributors add @bilgin-kocak for code

**Pull request merged**
